name: breastfeeding_notebook
channels:
  - defaults
  - conda-forge
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - colorama=0.4.4
  - cycler=0.10.0
  - decorator=5.0.7
  - defusedxml=0.7.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - freetype=2.10.4
  - icu=68.1
  - importlib-metadata=4.0.1
  - intel-openmp=2021.2.0
  - ipykernel=5.5.3
  - ipython=7.23.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.6.3
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.4
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.3.0
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.1.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - pycparser=2.20
  - pygments=2.8.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=300
  - pywinpty=1.0.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.35.5
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - arrow==1.1.0
    - astor==0.8.1
    - binaryornot==0.4.4
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - coloredlogs==15.0
    - cookiecutter==1.7.2
    - cryptography==3.4.7
    - daff==1.3.46
    - dask==2021.4.1
    - ddf-utils==1.0.12
    - fsspec==2021.4.0
    - funcparserlib==0.3.6
    - gitdb==4.0.7
    - gitpython==3.1.14
    - humanfriendly==9.1
    - hy==0.20.0
    - idna==2.10
    - jinja2-time==0.2.0
    - joblib==1.0.1
    - locket==0.2.1
    - orderedattrdict==1.6.0
    - partd==1.2.0
    - poyo==0.5.0
    - pyopenssl==20.0.1
    - pyreadline==2.1
    - python-graphviz==0.16
    - python-slugify==5.0.0
    - requests==2.25.1
    - rply==0.7.8
    - ruamel-yaml==0.17.4
    - ruamel-yaml-clib==0.2.2
    - smmap==4.0.0
    - tabulate==0.8.9
    - text-unidecode==1.3
    - toolz==0.11.1
    - tqdm==4.60.0
    - typing==3.7.4.3
    - unidecode==1.2.0
    - urllib3==1.26.4
